### ISSUE TITLE
 yolo_opencv.py  not find in the repertory 

### ISSUE THREAD

**Issue by ibrandiay** [Gidrian/Mediapipe-YOLO_Multiperson#1]
yolo_opencv.py  not find in the repertory  , please add this file please

**Comment by Gidrian** [comment]
It doesn't let me post files of more than 25 mb, I'll work on that.. I actualized the repo, download the folder +  [https://drive.google.com/file/d/1rlXLjlhmYNtsBPSFwG_ZiYHUmhO8POBH/view?usp=sharing](this file) and it should work

**Comment by ibrandiay** [comment]
Thanks !!
